# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for master

on:
    push:
        branches:
            - 'master' # 只针对 dev 分支
        paths:
            - '.github/workflows/*'
            # - '__test__/**' # dev 不需要立即测试
            - 'src/**'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'bin/*'

jobs:
    deploy-master:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.ALI}}" > ~/.ssh/id_rsa 
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "47.93.10.229" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              # 重新下载最新代码
              # 删除 origin ，否则会暴露 github 密码'
              # 和 docker-compose.yml service 名字一致
              run: |
                  ssh yq@47.93.10.229 "
                    cd /home/yq/lego-editor/lego-editer-server;
                    git remote add origin https://github.com/smokyfog/lego-editer-server.git;
                    git checkout master;
                    git pull origin master; 
                    git remote remove origin; 
                  
                    docker-compose build editor-server; 
                    docker-compose up -d;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
